### ISSUE TITLE
Overflow scroll UI 

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/itk-viewer-bootstrap-ui#110]
With an intensity image and a label image and a short viewer height, the elements go beyond the viewer. Perhaps we should scroll in this case? Or something better? Observed with itkwidgets. @PaulHax could you please take a look?

**Comment by PaulHax** [comment]
I simplified the overflow behavior in #111.  I think this will catch the problem but I could only reproduce by artificially increasing an element's size in UI in Juypter Notebook via dev-tools.
