### ISSUE TITLE
Slicer clicks not registered

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/itk-viewer-bootstrap-ui#115]
With the latest itkwidgets (and itk-vtk-viewer, itk-viewer-bootstrap-ui), slider clicks are not registered:

https://user-images.githubusercontent.com/25432/192307409-36875db5-3dd3-4041-b37f-cf8464387627.mp4

**Comment by PaulHax** [comment]
A bad one.  PR open.
