### ISSUE TITLE
Show Index, Position, Value for 3D object

### ISSUE THREAD

**Issue by labdala** [InsightSoftwareConsortium/itk-viewer-bootstrap-ui#22]
The [original app](https://kitware.github.io/itk-vtk-viewer/app/) shows the Index, Position and Value as we drag the mouse over the 3D object (`Volume [4]` mode). We could recover such feature for this version of the app.

**Comment by PaulHax** [comment]
When the the slice planes are shown, I see that information in this repo.  The app only shows that info when the slice plains are shown.

**Comment by labdala** [comment]
That's right. Closing it.
