### ISSUE TITLE
Fix black cube that gets rendered before the image does

### ISSUE THREAD

**Issue by labdala** [InsightSoftwareConsortium/itk-viewer-bootstrap-ui#49]

**Comment by thewtex** [comment]
Please try updating the version of itk-vtk-viewer used in the testing index.html.

**Comment by labdala** [comment]
@thewtex by changing its version to the current one 14.1.0:
```
src="https://cdn.jsdelivr.net/npm/itk-vtk-viewer@14.1.0/dist/itkVtkViewer.js"
```
I get the error message: 
 "itkVtkViewer is not defined".

I confirmed this version is available in [JSDelivr](https://www.jsdelivr.com/package/npm/itk-vtk-viewer). Any insights on this issue?

**Comment by PaulHax** [comment]
https://github.com/Kitware/itk-vtk-viewer/issues/514

**Comment by PaulHax** [comment]
`https://cdn.jsdelivr.net/npm/itk-vtk-viewer@14.2.0/dist/itkVtkViewer.min.js` is up now.

**Comment by labdala** [comment]
Amazing! Thank you @PaulHax and @thewtex
