### ISSUE TITLE
Add ImJoy to jupyterlite build

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/itk-viewer-bootstrap-ui#54]
See: https://github.com/imjoy-team/jupyter.imjoy.io

@oeway

**Comment by thewtex** [comment]
@labdala 

- [ ] Take a look at the [itkwidgets jupyterlite documentation](https://itkwidgets.readthedocs.io/en/latest/deployments.html#jupyterlite) and deploy jupyterlite on this repository's documentation
- [ ] Add an initialization option to itkwidgets to specify the UI with a string. When it is `'pydata-sphinx'`, have the itk-vtk-viewer use the ui JS module from this package on jsdelivr

**Comment by oeway** [comment]
FYI: It looks like the jupyterlite URL is broken at the moment: https://itkwidgets.readthedocs.io/en/latest/_static/lab/index.html

**Comment by thewtex** [comment]
@oeway @labdala yes, there were a few issues with RTD / Sphinx -- resolved now :-)

**Comment by labdala** [comment]
Accomplished in #60.
Thank you very much @thewtex and @oeway.
