### ISSUE TITLE
Modify rangeMin, rangeMax declaration in ColorRangeInput.js 

### ISSUE THREAD

**Issue by labdala** [InsightSoftwareConsortium/itk-viewer-bootstrap-ui#59]
`actorContext.image.scaleInfo[actorContext.renderedScale].ranges[actorContext.selectedComponent]` 
is undefined for some datasets (e.g., astronaut.zarr)

**Comment by PaulHax** [comment]
The viewer computes the range asynchronously after the image is loaded.  It could be the component renders before this happens.  Perhaps we need to useSelector for the `selectedRange`
