### ISSUE TITLE
Update itkwidgets wheel once 1.0a7 or 1.0a8 is out

### ISSUE THREAD

**Issue by labdala** [InsightSoftwareConsortium/itk-viewer-bootstrap-ui#81]

**Comment by labdala** [comment]
- [ ] If [c20288683ef8cbc6a7e2df0264984253a7d55bd4](https://github.com/InsightSoftwareConsortium/itkwidgets/commit/c20288683ef8cbc6a7e2df0264984253a7d55bd4) is included in the release,  update screenshot for PCA example using different colors for each point set

**Comment by thewtex** [comment]
And use `==` on the versions in the `piplite.install`.

**Comment by thewtex** [comment]
We have 1.0a7 per #85 , should update to 1.0a8 after it is out.
